import '../css/bootstrap.scss'
import 'popper.js'
import 'bootstrap'
import '@danielfarrell/bootstrap-combobox/css/bootstrap-combobox.css'
import '@danielfarrell/bootstrap-combobox/js/bootstrap-combobox.js'
